### ISSUE TITLE
I am 10 hours late :)

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/adminerevo_ynh#2]
timing... I was about to update adminer_ynh with the AdminerEvo repo -> https://github.com/YunoHost-Apps/adminer_ynh/pull/28

I have added the repo to catalog: https://github.com/YunoHost/apps/pull/2543

**Comment by CodeShakingSheep** [comment]
Haha funny that we had the same idea about adding AdminerEvo. Thanks for adding the repo to the catalog and for picking this up and creating another PR in this repo. :raised_hands:
