### ISSUE TITLE
Why is AdminerEvo flagged as broken?

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/adminerevo_ynh#6]
When I want to install AdminerEvo, I see the "broken" label. See screenshot.
![image](https://github.com/user-attachments/assets/f13defbe-788e-44e4-ba2b-8cf7ecfdc09b)

In `apps.toml` the state is `working`. See https://github.com/YunoHost/apps/blob/master/apps.toml#L83
Any idea about that @ericgaspar ?

**Comment by ericgaspar** [comment]
New app that needs to go through the validation system I guess...

**Comment by CodeShakingSheep** [comment]
Alright, how long does the validation process usually take? I also checked for example [HotGlue](https://github.com/YunoHost-Apps/hotglue_ynh) which got added to the catalog 2 weeks ago and it's also flagged as broken (although its label is "Just got added to the catalog"). So, I can assume as long as apps have this label "Just got added to the catalog" they are flagged as broken?

**Comment by CodeShakingSheep** [comment]
Ok, it doesn't appear as broken anymore.
![image](https://github.com/user-attachments/assets/e08c5a21-4a6c-4ed6-ae38-8ec8cb267b5a)

**Comment by OniriCorpe** [comment]
It was an issue on our infra btw, now the catalog should be updated as usual
